### PR TITLE
fix: fix popover eslint errors

### PR DESCRIPTION
**Pull request by banlify**

### CODE REVIEW

**Comment by banlify** [comment]
@banlify for code

**Review by kagol — APPROVED** [review]

**Comment by kagol** [comment]
> @banlify for code

需要@all-contributors，这样机器人才能感知到

**Comment by kagol** [comment]
@all-contributors please add @banlify for code

**Comment by banlify** [comment]
> @banlify for code
> 
> 需要@all-contributors，这样机器人才能感知到

原来是这样 :P

**Pull request merged**
