### PR TITLE
feat(popover):  popover show hide method

### PR DESCRIPTION
**Pull request by lj1990111**

### CODE REVIEW

**Comment by kagol** [comment]
@lj1990111 希望补充下单元测试用例🤝

**Comment by kagol** [comment]
@all-contributor please add @lj1990111 for code.

**Comment by kagol** [comment]
@all-contributors please add @lj1990111 for code.

**Comment by xingyan95** [comment]
@lj1990111 文档中需要补充下暴露出来的事件说明哈，类似下图这样
image

**Review by kagol — APPROVED** [review]

**Pull request merged**
