### PR TITLE
【alter】修复设置dismissTimer后提前点击close报错,空样式问题

### PR DESCRIPTION
**Pull request by classheadmaster**

### CODE REVIEW

**Review by ElsaOOo — APPROVED** [review]

**Comment by ElsaOOo** [comment]
@classheadmaster  提交的时候需要设置一下commit signature， 参考一下 https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification 这个文档~

**Comment by classheadmaster** [comment]
@ElsaOOo 已重新提交了pr： #15

**Comment by kagol** [comment]
@all-contributors please add @ElsaOOo for infra and code

**Comment by kagol** [comment]
@all-contributors please add @ElsaOOo for maintenance

**Comment by kagol** [comment]
@all-contributors please add @ElsaOOo for maintenance

**Pull request closed without merging**
